POST http://localhost:8080/subscriber/create
Content-Type: application/json

{
    "name": "*",
    "channel": "*"
}

###

GET http://localhost:8080/subscriber/list

###
GET http://localhost:8080/subscriber/id

###
PATCH http://localhost:8080/subscriber/id
Content-Type: application/json

{
    "channel": "*",

}


###
DELETE http://localhost:8080/subscriber/id